window.SPEEDINCAR_INVENTORY = [
  {
    id: 'scirocco',
    category: 'hatchback',
    brand: 'Volkswagen',
    model: 'Scirocco',
    year: 2017,
    km: 118000,
    price: 14800000,
    status: 'Disponible',
    fuel: 'Bencina',
    engine: '1.4 Turbo TSI',
    transmission: 'DSG autom\u00e1tico',
    traction: 'Delantera',
    body: 'Coupe',
    location: 'Santiago',
    cover: 'images/scirocco.png',
    images: ['images/scirocco.png'],
    tags: ['Turbo', 'DSG', 'Revisi\u00f3n al d\u00eda'],
    highlights: [
      'Motor 1.4 Turbo TSI 122 HP',
      'Caja DSG de doble embrague',
      'Control crucero',
      'Pantalla multimedia',
      'Revisi\u00f3n t\u00e9cnica al d\u00eda',
    ],
    featured: true,
  },
  {
    id: 'tucson',
    category: 'suv',
    brand: 'Hyundai',
    model: 'Tucson TL',
    year: 2018,
    km: 55000,
    price: 13000000,
    status: 'Disponible',
    fuel: 'Bencina',
    engine: '2.0 GDI',
    transmission: 'Manual 6 velocidades',
    traction: '4x2',
    body: 'SUV',
    location: 'Santiago',
    cover: 'images/tucson.png',
    images: ['images/tucson.png'],
    tags: ['55.000 km', '2.0 GDI', '4x2'],
    highlights: [
      'Motor 2.0 GDI 150 HP',
      'C\u00e1mara de retroceso',
      'Climatizador autom\u00e1tico',
      'Control de estabilidad ESC',
      'Revisi\u00f3n t\u00e9cnica al d\u00eda',
    ],
    featured: true,
  },
  {
    id: 'grand-creta',
    category: 'suv',
    brand: 'Hyundai',
    model: 'Grand Creta',
    year: 2024,
    km: 15500,
    price: 18500000,
    status: 'Disponible',
    fuel: 'Bencina',
    engine: '2.0 MPI',
    transmission: 'Autom\u00e1tica 6 velocidades',
    traction: 'Delantera',
    body: 'SUV',
    location: 'Santiago',
    cover: 'images/grandcreta.png',
    images: ['images/grandcreta.png'],
    tags: ['2024', 'Autom\u00e1tica', '3 filas'],
    highlights: [
      'Motor 2.0 MPI 165 HP',
      'Pantalla t\u00e1ctil 10.25 pulgadas',
      'Apple CarPlay y Android Auto',
      'Control crucero adaptativo',
      'Solo 15.500 km',
    ],
    featured: true,
  },
  {
    id: 'mokka',
    category: 'suv',
    brand: 'Opel',
    model: 'Mokka Elegance',
    year: 2025,
    km: 3600,
    price: 16800000,
    status: 'Disponible',
    fuel: 'Bencina',
    engine: '1.2 Turbo',
    transmission: 'Autom\u00e1tica 8 velocidades',
    traction: 'Delantera',
    body: 'SUV compacto',
    location: 'Santiago',
    cover: 'images/mokka.png',
    images: ['images/mokka.png'],
    tags: ['2025', '1.2 Turbo', 'Como nuevo'],
    highlights: [
      'Motor 1.2 Turbo 130 HP',
      'Caja autom\u00e1tica 8 velocidades',
      'Adaptive Cruise Control',
      'Asientos calefaccionados',
      'Solo 3.600 km',
    ],
    featured: false,
  },
  {
    id: 'evoltis',
    category: 'suv',
    brand: 'Subaru',
    model: 'Evoltis Limited AWD',
    year: 2021,
    km: 60000,
    price: 24500000,
    status: 'Disponible',
    fuel: 'Bencina',
    engine: '2.5 Boxer',
    transmission: 'Autom\u00e1tica CVT',
    traction: 'AWD sim\u00e9trica',
    body: 'SUV familiar',
    location: 'Santiago',
    cover: 'images/evoltis.png',
    images: ['images/evoltis.png'],
    tags: ['AWD', 'Limited', 'Familiar'],
    highlights: [
      'Motor Boxer 2.5L 185 HP',
      'Tracci\u00f3n AWD sim\u00e9trica permanente',
      'EyeSight seguridad activa',
      'Cuero con calefacci\u00f3n',
      'Panoramic Moonroof',
    ],
    featured: false,
  },
];
